title: Liquip
description: >-
  The Liquip project-page.
baseurl: "/"
url: "https://liquip.github.io"
github_username:  liquip

remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    github: liquip
plugins:
  - jekyll-feed

lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
