title: Liquip
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/"
url: "https://liquip.github.io"
github_username:  liquip

theme: minima
minima:
  skin: dark
  social_links:
    github: liquip
plugins:
  - jekyll-feed

lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
